import { Schema as S } from 'effect';

export const Model = S.Struct({
	data: S.NullOr(S.Unknown),
	diff: S.NullOr(S.Unknown),
	query: S.String,
	revset: S.String,
	path: S.String,
	after: S.String,
	until: S.String,
	searchMode: S.Literals(['all', 'metadata', 'changes', 'snapshot']),
	matchMode: S.Literals(['literal', 'regex', 'fuzzy']),
	searchResults: S.NullOr(S.Unknown),
	searchLoading: S.Boolean,
	searchRequestId: S.Number,
	searchError: S.String,
	relatedExpanded: S.Boolean,
	selectedIndex: S.Number,
	oldestFirst: S.Boolean,
	loading: S.Boolean,
	error: S.String,
	compact: S.Boolean,
});
export type Model = typeof Model.Type;

export const initialModel: Model = {
	data: null,
	diff: null,
	query: '',
	revset: 'ancestors(@)',
	path: '',
	after: '',
	until: '',
	searchMode: 'metadata',
	matchMode: 'literal',
	searchResults: null,
	searchLoading: false,
	searchRequestId: 0,
	searchError: '',
	relatedExpanded: false,
	selectedIndex: 0,
	oldestFirst: false,
	loading: true,
	error: '',
	compact: false,
};
