import { Option, Schema as S } from 'effect';
import { DragIdle, DragState } from './machine/drag.ts';
import { Closed, OverlayState } from './machine/overlay.ts';
import { SelectionState } from './machine/selection.ts';
import { SessionState } from './machine/session.ts';

export const ComparisonMode = S.Literals(['range', 'step']);
export const ComparisonSource = S.Literals(['revision', 'snapshot']);
export const LayoutMode = S.Literals(['split', 'unified']);
export const ContentMode = S.Literals(['diffs', 'full']);
export const Preset = S.Literals(['year', '7d', '30d', '90d', 'all']);
export const FileSwitcherMode = S.Literals(['workspace', 'overview']);
export const ThemePreference = S.Literals(['auto', 'light', 'dark']);

// Range tooltip payload — only fields the view needs to lay out and label the tooltip.
// Entries/preview are looked up from `data`/`previewByRange` at view time.
export const TrackTooltipState = S.Struct({
	left: S.Number,
	top: S.Number,
	fromIndex: S.Number,
	toIndex: S.Number,
	pending: S.Boolean,
	selectedCount: S.Number,
});
export type TrackTooltipState = typeof TrackTooltipState.Type;

// Complex host-shaped values. We keep Model Schema-based but treat these payloads as opaque
// because their nested arrays and maps are validated at the host boundary.
export const Model = S.Struct({
	session: SessionState,
	selection: SelectionState,
	overlay: OverlayState,
	data: S.NullOr(S.Unknown),
	fromIndex: S.Number,
	toIndex: S.Number,
	comparisonMode: ComparisonMode,
	comparisonSource: ComparisonSource,
	layoutMode: LayoutMode,
	contentMode: ContentMode,
	preset: Preset,
	showIntermediateRevisions: S.Boolean,
	customRevset: S.String,
	rangeStackOpen: S.Boolean,
	rangeStackByPath: S.Record(S.String, S.Unknown),
	blameOverlayOpen: S.Boolean,
	blameLines: S.Unknown,
	blameLoading: S.Boolean,
	historySearchQuery: S.String,
	historySearchLoading: S.Boolean,
	historySearchResult: S.NullOr(S.Unknown),
	timeLapsePlaying: S.Boolean,
	sidebarSearchQuery: S.String,
	sidebarContentNeedle: S.String,
	sidebarContentMatchIndexes: S.Array(S.Number),
	sidebarContentLoading: S.Boolean,
	sidebarWidth: S.Number,
	sidebarCollapsed: S.Boolean,
	responsiveSidebarHeight: S.Number,
	timelinePaneHeight: S.Number,
	timelinePaneCollapsed: S.Boolean,
	themePreference: ThemePreference,
	diffFocusMode: S.Boolean,
	actionsMenuOpen: S.Boolean,
	viewMenuOpen: S.Boolean,
	hotkeysOpen: S.Boolean,
	oldestFirst: S.Boolean,
	fileInputValue: S.String,
	fromRevisionDraft: S.String,
	toRevisionDraft: S.String,
	openComboboxId: S.Option(S.String),
	fileSwitcherMode: FileSwitcherMode,
	rangeOverviewByRange: S.Record(S.String, S.Unknown),
	rangeOverviewLoadingKey: S.String,
	entryDiffCountByKey: S.Record(S.String, S.Number),
	entryDiffCountLoadingKey: S.String,
	previewByRange: S.Record(S.String, S.Unknown),
	sidebarPreviewInFlightKey: S.String,
	sidebarPreviewInFlightKeys: S.Record(S.String, S.Boolean),
	fileSessionByPath: S.Record(S.String, S.Unknown),
	pendingRangeResolutionKey: S.String,
	maybeHoveredSelectionIndex: S.Option(S.Number),
	maybeTrackTooltip: S.Option(TrackTooltipState),
	shortcutFocusedInputId: S.Option(S.String),
	sessionKey: S.Number,
	previewRequestId: S.Number,
	dragState: DragState,
	suppressAnchorClick: S.Boolean,
});
export type Model = typeof Model.Type;

export const initialModel: Model = {
	session: { _tag: 'Idle' },
	selection: { _tag: 'IdlePick' },
	overlay: Closed(),
	data: null,
	fromIndex: 0,
	toIndex: 0,
	comparisonMode: 'range',
	comparisonSource: 'revision',
	layoutMode: 'split',
	contentMode: 'diffs',
	preset: 'year',
	showIntermediateRevisions: false,
	customRevset: '',
	rangeStackOpen: false,
	rangeStackByPath: {},
	blameOverlayOpen: false,
	blameLines: [],
	blameLoading: false,
	historySearchQuery: '',
	historySearchLoading: false,
	historySearchResult: null,
	timeLapsePlaying: false,
	sidebarSearchQuery: '',
	sidebarContentNeedle: '',
	sidebarContentMatchIndexes: [],
	sidebarContentLoading: false,
	sidebarWidth: 280,
	sidebarCollapsed: false,
	responsiveSidebarHeight: 248,
	timelinePaneHeight: 220,
	timelinePaneCollapsed: false,
	themePreference: 'auto',
	diffFocusMode: false,
	actionsMenuOpen: false,
	viewMenuOpen: false,
	hotkeysOpen: false,
	oldestFirst: false,
	fileInputValue: '',
	fromRevisionDraft: '',
	toRevisionDraft: '',
	openComboboxId: Option.none(),
	fileSwitcherMode: 'workspace',
	rangeOverviewByRange: {},
	rangeOverviewLoadingKey: '',
	entryDiffCountByKey: {},
	entryDiffCountLoadingKey: '',
	previewByRange: {},
	sidebarPreviewInFlightKey: '',
	sidebarPreviewInFlightKeys: {},
	fileSessionByPath: {},
	pendingRangeResolutionKey: '',
	maybeHoveredSelectionIndex: Option.none(),
	maybeTrackTooltip: Option.none(),
	shortcutFocusedInputId: Option.none(),
	sessionKey: 0,
	previewRequestId: 0,
	dragState: DragIdle(),
	suppressAnchorClick: false,
};
